application: tuxv-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

# Handler for css dir 
- url: /css
  static_dir: css

# Handler for fonts dir 
- url: /font
  static_dir: font

# Handler for dir containing images
- url: /img
  static_dir: img

# Handler for dir containing javascript
- url: /js
  static_dir: js

# Handler for dir containing plugins
- url: /plugins
  static_dir: plugins

# Handler for dir with static files
- url: /static
  static_dir: static

# Web frontend
- url: /.*
  script: index.app 

libraries:
  
# For the templates
- name: jinja2
  version: latest
